[package]
name = "datacore"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
arrow = { version = "51.0", features = ["prettyprint"] }
parquet = { version = "51.0" }
datafusion = "38.0"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.8", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
byteorder = "1.5"
rand = "0.8"

# Hardware-accelerated Cryptography (AES-256-CTR for Hadoop KMS Envelope Encryption)
aes = "0.8"
ctr = "0.9"

# Prometheus Exporter
prometheus = { version = "0.13", features = ["process"] }

# HTTP & WebHDFS Client
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }

# LDAP/S Protocol Client
ldap3 = { version = "0.11", default-features = false, features = ["tls-rustls"] }

# Portal & API Engine
axum = "0.7"
tower-http = { version = "0.5", features = ["cors"] }
